# Generated by Django 5.2.12 on 2026-03-16 19:40

import apps.catalogue.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('family', models.CharField(choices=[('keyboard', 'Keyboard'), ('strings', 'Strings'), ('woodwind', 'Woodwind'), ('brass', 'Brass'), ('percussion', 'Percussion'), ('voice', 'Voice'), ('ensemble', 'Orchestra / Band / Ensemble')], max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['family', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalogue.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('composer', models.CharField(max_length=255)),
                ('lyricist', models.CharField(blank=True, max_length=255)),
                ('arranger', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('year_published', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decade', models.CharField(blank=True, editable=False, max_length=10)),
                ('ensemble_type', models.CharField(blank=True, choices=[('solo', 'Solo'), ('duo', 'Duo'), ('trio', 'Trio'), ('quartet', 'Quartet'), ('quintet', 'Quintet'), ('voice_piano', 'Voice & Piano'), ('chamber', 'Chamber Group'), ('orchestra', 'Orchestra'), ('band', 'Band'), ('choir', 'Choir'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.catalogue.models.sheet_music_cover_path)),
                ('preview_image', models.ImageField(blank=True, editable=False, upload_to=apps.catalogue.models.sheet_music_preview_image_path)),
                ('preview_pdf', models.FileField(blank=True, editable=False, upload_to=apps.catalogue.models.sheet_music_preview_pdf_path)),
                ('audio_sample', models.FileField(blank=True, upload_to=apps.catalogue.models.sheet_music_audio_path)),
                ('pdf_file', models.FileField(blank=True, upload_to=apps.catalogue.models.sheet_music_pdf_path)),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='sheet_music', to='catalogue.category')),
                ('genres', models.ManyToManyField(blank=True, related_name='sheet_music', to='catalogue.genre')),
                ('instruments', models.ManyToManyField(blank=True, related_name='sheet_music', to='catalogue.instrument')),
            ],
            options={
                'verbose_name': 'Sheet Music',
                'verbose_name_plural': 'Sheet Music',
                'ordering': ['-created_at'],
            },
        ),
    ]
