# Generated by Django 5.2.12 on 2026-03-19 08:57

import apps.catalogue.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_seed_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='pdf_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='/Users/michaelpiraner/Projects/AntiqueTunes/protected_media'), upload_to=apps.catalogue.models.sheet_music_pdf_path),
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.catalogue.models.bundle_cover_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='bundles', to='catalogue.sheetmusic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
